services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env.prod
    environment:
      DATABASE_URL: sqlite+aiosqlite:///./data/quiz.db
      ENVIRONMENT: prod
      COOKIE_SECURE: "true"
      FRONTEND_ORIGINS: "http://localhost,http://127.0.0.1, http://pbiritrtf"
    volumes:
      - backend_data:/app/data
    expose:
      - "8000"
    ports:
      - "8000:8000"

volumes:
  backend_data:
